import { StylePreset } from '../types/dock';

export const STYLE_PRESETS: StylePreset[] = [
  {
    id: 'organic-onyx',
    name: 'Orgânico Onyx',
    category: 'Bézier Clássico',
    description: 'Silhueta fluida inspirada em gota d\'água com preto profundo OLED e expansão morphing.',
    shape: 'drop',
    theme: 'onyx',
    defaultDisplayMode: 'morph',
    width: 130,
    expandedWidth: 380,
    tension: 1.0,
    wallpaper: 'obsidian',
  },
  {
    id: 'frost-glass',
    name: 'Vidro Acetinado (Glassmorphism)',
    category: 'Translúcido Moderno',
    description: 'Backdrop blur aerado com reflexo de luz especular e contorno translúcido.',
    shape: 'leaf',
    theme: 'glass',
    defaultDisplayMode: 'morph',
    width: 130,
    expandedWidth: 390,
    tension: 1.1,
    wallpaper: 'cosmic',
  },
  {
    id: 'cyber-stealth',
    name: 'Cyber Stealth HUD',
    category: 'Sci-Fi / Tático',
    description: 'Chanfros poliédricos angulares com linhas de precisão militar e acentos neon.',
    shape: 'cyber',
    theme: 'cyberpunk',
    defaultDisplayMode: 'morph',
    width: 135,
    expandedWidth: 400,
    tension: 1.0,
    wallpaper: 'aurora',
  },
  {
    id: 'macos-floating',
    name: 'Cápsula Flutuante',
    category: 'Minimalista Apple-Like',
    description: 'Pílula aerada superelíptica que flutua junto à borda da tela com acabamento suave.',
    shape: 'capsule',
    theme: 'nordic',
    defaultDisplayMode: 'morph',
    width: 125,
    expandedWidth: 370,
    tension: 0.9,
    wallpaper: 'slate',
  },
  {
    id: 'amber-terminal',
    name: 'Âmbar Retro Industrial',
    category: 'Analógico & Synth',
    description: 'Tons quentes monocromáticos com sensação tátil de instrumento de alta precisão.',
    shape: 'feather',
    theme: 'amber',
    defaultDisplayMode: 'morph',
    width: 130,
    expandedWidth: 390,
    tension: 1.0,
    wallpaper: 'obsidian',
  },
  {
    id: 'split-drawer',
    name: 'Onda Harmônica Midnight',
    category: 'Biomórfico Dinâmico',
    description: 'Ondulação dupla sinuosa com degradê roxo crepúsculo e flyout expansivo.',
    shape: 'wave',
    theme: 'midnight',
    defaultDisplayMode: 'morph',
    width: 130,
    expandedWidth: 390,
    tension: 1.15,
    wallpaper: 'cosmic',
  },
];
